[package]
name = "gb-rust-frontend"
version = "0.1.0"
authors = ["Agi Sferro <agi.novanta@gmail.com>"]

[dependencies]
glium = "0.25.1"
clap = "2.20.3"
sdl2 = "0.32.2"
image = "0.22.3"
gb = { path = "../core", features = ["debugger"] }
