[package]
name = "gb-rust-frontend"
version = "0.1.0"
authors = ["Giovanni Sferro <agi.novanta@gmail.com>"]

[dependencies]
glium = "0.16"
clap = "2.20.3"
sdl2 = "0.28.0"
gb = { path = "../gb-rust-core", features = ["debugger"] }
